--第一題
SELECT DISTINCT KEEPER_ID AS [KeeperId],USER_CNAME AS [CName],USER_ENAME [EName],YEAR(LEND_DATE) AS [BorrowYear],COUNT(USER_ID) AS [BorrowCnt]
FROM BOOK_LEND_RECORD,MEMBER_M 
WHERE KEEPER_ID = USER_ID
GROUP BY KEEPER_ID,USER_CNAME,USER_ENAME,YEAR(LEND_DATE)
ORDER BY KEEPER_ID ,USER_ENAME,YEAR(LEND_DATE)

SELECT DISTINCT KEEPER_ID AS [KeeperId],USER_CNAME AS [CName],USER_ENAME [EName],YEAR(LEND_DATE) AS [BorrowYear],COUNT(USER_ID) AS [BorrowCnt]
FROM BOOK_LEND_RECORD blr
INNER JOIN MEMBER_M mm on blr.KEEPER_ID = mm.USER_ID
GROUP BY KEEPER_ID,USER_CNAME,USER_ENAME,YEAR(LEND_DATE)
ORDER BY KEEPER_ID ,USER_ENAME,YEAR(LEND_DATE)

--第二題

SELECT TOP(5)blr.BOOK_ID,bd.BOOK_NAME,COUNT(blr.KEEPER_ID) AS [QTY] 
FROM BOOK_LEND_RECORD blr,BOOK_DATA bd
WHERE bd.BOOK_ID = blr.BOOK_ID
GROUP BY blr.BOOK_ID,bd.BOOK_NAME
ORDER BY QTY DESC

SELECT TOP(5)blr.BOOK_ID,bd.BOOK_NAME,COUNT(blr.KEEPER_ID) AS [QTY] 
FROM BOOK_LEND_RECORD blr
INNER JOIN BOOK_DATA bd on bd.BOOK_ID = blr.BOOK_ID
GROUP BY blr.BOOK_ID,bd.BOOK_NAME
ORDER BY QTY DESC

--3
SELECT 
CASE 
	WHEN NTILE(4) OVER ( ORDER BY LEND_DATE)=1 THEN '2019/01~2019/03'
	WHEN NTILE(4) OVER ( ORDER BY LEND_DATE)=2 THEN '2019/04~2019/06'
	WHEN NTILE(4) OVER ( ORDER BY LEND_DATE)=3 THEN '2019/07~2019/09'
	WHEN NTILE(4) OVER ( ORDER BY LEND_DATE)=4 THEN '2019/10~2019/12'
	-- ELSE
END AS [quarter],
CASE 
	WHEN '1' THEN COUNT(LEND_DATE)
END AS [Cnt]
--SELECT LEND_DATE,COUNT(BOOK_ID)
FROM BOOK_LEND_RECORD 
WHERE YEAR(LEND_DATE)='2019'
GROUP BY BOOK_LEND_RECORD.LEND_DATE
	
--第三題--------
SELECT a.Quarter,
	CASE Quarter
	WHEN '2019/01~2019/03' THEN SUM(A.CNT)
	WHEN '2019/04~2019/06' THEN SUM(A.CNT)
	WHEN '2019/07~2019/09' THEN SUM(A.CNT)
	WHEN '2019/10~2019/12' THEN SUM(A.CNT)
END AS [Cnt]
FROM 
(SELECT 
CASE 
	WHEN MONTH(LEND_DATE)>='01'AND MONTH(LEND_DATE)<='03' THEN '2019/01~2019/03'
	WHEN MONTH(LEND_DATE)>='04'AND MONTH(LEND_DATE)<='06' THEN '2019/04~2019/06'
	WHEN MONTH(LEND_DATE)>='07'AND MONTH(LEND_DATE)<='09' THEN '2019/07~2019/09'
	WHEN MONTH(LEND_DATE)>='010'AND MONTH(LEND_DATE)<='12' THEN '2019/10~2019/12'
	-- ELSE
END AS [Quarter],LEND_DATE,COUNT(LEND_DATE) AS [CNT]
FROM BOOK_LEND_RECORD 
WHERE YEAR(LEND_DATE)='2019'
GROUP BY BOOK_LEND_RECORD.LEND_DATE
)AS A
GROUP BY A.Quarter

--第四題
;WITH CTEDATA AS
	  (
(SELECT ROW_NUMBER() OVER (PARTITION BY bC.BOOK_CLASS_NAME ORDER BY COUNT(blr.BOOK_ID) DESC)AS [Seq],
		bc.BOOK_CLASS_NAME AS [BOOKCLASS],
		blr.BOOK_ID AS [BOOKID],
		bd.BOOK_NAME AS [BOOKNAME],
		COUNT(blr.BOOK_ID) AS [Cnt]
FROM BOOK_LEND_RECORD blr,BOOK_CLASS bc,BOOK_DATA bd
WHERE bd.BOOK_ID=blr.BOOK_ID
	AND bc.BOOK_CLASS_ID = bd.BOOK_CLASS_ID
GROUP BY bc.BOOK_CLASS_NAME,blr.BOOK_ID,bd.BOOK_NAME,bd.BOOK_CLASS_ID
/*ORDER BY bc.BOOK_CLASS_NAME,[Cnt] DESC*/)
)
SELECT Seq,BOOKCLASS,BOOKID,BOOKNAME,Cnt
FROM CTEDATA
WHERE Seq<4 
ORDER BY BOOKCLASS,Cnt DESC,BOOKID

  --------    
SELECT ROW_NUMBER() OVER (PARTITION BY bC.BOOK_CLASS_NAME ORDER BY COUNT(blr.BOOK_ID) DESC)AS [Seq],
		bc.BOOK_CLASS_NAME,blr.BOOK_ID,bd.BOOK_NAME,COUNT(blr.BOOK_ID) AS [Cnt]
FROM BOOK_LEND_RECORD blr,BOOK_CLASS bc,BOOK_DATA bd
WHERE bd.BOOK_ID=blr.BOOK_ID
	AND bc.BOOK_CLASS_ID = bd.BOOK_CLASS_ID
GROUP BY bc.BOOK_CLASS_NAME,blr.BOOK_ID,bd.BOOK_NAME,bd.BOOK_CLASS_ID
ORDER BY bc.BOOK_CLASS_NAME,[Cnt] DESC



--TRY
SELECT NTILE(5)OVER(ORDER BY COUNT(blr.BOOK_ID) DESC),bc.BOOK_CLASS_NAME,blr.BOOK_ID,bd.BOOK_NAME,COUNT(blr.BOOK_ID) AS [Cnt]		
FROM BOOK_LEND_RECORD blr,BOOK_CLASS bc,BOOK_DATA bd
WHERE bd.BOOK_ID=blr.BOOK_ID
	AND bc.BOOK_CLASS_ID = bd.BOOK_CLASS_ID
GROUP BY bc.BOOK_CLASS_NAME,blr.BOOK_ID,bd.BOOK_NAME
ORDER BY bc.BOOK_CLASS_NAME,[Cnt] DESC

--5,6
SELECT  bc.BOOK_CLASS_ID,bc.BOOK_CLASS_NAME,COUNT(*),YEAR(blr.LEND_DATE)AS [YEAR]
FROM BOOK_LEND_RECORD blr ,BOOK_DATA bd,BOOK_CLASS bc
WHERE blr.BOOK_ID=bd.BOOK_ID
	AND bd.BOOK_CLASS_ID = bc.BOOK_CLASS_ID
	OR bc.BOOK_CLASS_ID IS NULL
GROUP BY bc.BOOK_CLASS_ID,bc.BOOK_CLASS_NAME,YEAR(blr.LEND_DATE)
--HAVING COUNT(bc.BOOK_CLASS_ID) IS NULL

--第五題
;WITH CTEDATA(CNT_YEAR,CLASSID,CLASSNAME) AS
	  (
	  SELECT YEAR(BLR.LEND_DATE)AS [CNT_YEAR],
			bc.BOOK_CLASS_ID AS [ClassId],
			BOOK_CLASS_NAME AS[ClassName]
	  FROM BOOK_LEND_RECORD blr
	  INNER JOIN BOOK_DATA bd ON blr.BOOK_ID=bd.BOOK_ID
	  INNER JOIN BOOK_CLASS bc ON bd.BOOK_CLASS_ID = bc.BOOK_CLASS_ID
)
SELECT CTEDATA.CLASSID,CTEDATA.CLASSNAME,
    COUNT(CASE CNT_YEAR	WHEN '2016' THEN CTEDATA.CLASSID  END) AS 'CNT2016',
    COUNT(CASE CNT_YEAR	WHEN '2017' THEN CTEDATA.CLASSID END)  AS 'CNT2017',
	COUNT(CASE CNT_YEAR	WHEN '2018' THEN CTEDATA.CLASSID  END) AS 'CNT2018',
	COUNT(CASE CNT_YEAR	WHEN '2019' THEN CTEDATA.CLASSID  END) AS 'CNT2019'

FROM  CTEDATA
GROUP BY CTEDATA.CLASSID,CTEDATA.CLASSNAME
ORDER BY CLASSID


--第六題

;WITH CTEDATA AS
	  (
	  SELECT YEAR(LEND_DATE)AS [CNT_YEAR],
			COUNT(bc.BOOK_CLASS_ID) AS [QTY],
			bc.BOOK_CLASS_ID AS [CLASSID],
			BOOK_CLASS_NAME AS[CLASSNAME]
	  FROM BOOK_LEND_RECORD blr,BOOK_CLASS bc,BOOK_DATA bd
	  WHERE blr.BOOK_ID=bd.BOOK_ID
		AND bd.BOOK_CLASS_ID = bc.BOOK_CLASS_ID
	 GROUP BY bc.BOOK_CLASS_ID,bc.BOOK_CLASS_NAME,YEAR(blr.LEND_DATE)
)
SELECT CLASSID,CLASSNAME ,ISNULL([2016],0)AS [Cnt2016],ISNULL([2017],0)AS [Cnt2017],ISNULL([2018],0)AS [Cnt2018],ISNULL([2019],0)AS [Cnt2019]
FROM (SELECT CLASSID,QTY,CNT_YEAR,CLASSNAME
      FROM CTEDATA) AS D
PIVOT(SUM(D.QTY) FOR D.CNT_YEAR
				IN([2016],[2017],[2018],[2019])
				) AS PVT
ORDER BY PVT.CLASSID;


-------CASE6-2
;WITH CTEDATA(CNT_YEAR,CLASSID,CLASSNAME) AS
	  (
	  SELECT YEAR(BLR.LEND_DATE)AS [CNT_YEAR],
			bc.BOOK_CLASS_ID AS [ClassId],
			BOOK_CLASS_NAME AS[ClassName]
	  FROM BOOK_LEND_RECORD blr
	  INNER JOIN BOOK_DATA bd ON blr.BOOK_ID=bd.BOOK_ID
	  INNER JOIN BOOK_CLASS bc ON bd.BOOK_CLASS_ID = bc.BOOK_CLASS_ID
)
SELECT CLASSID,CLASSNAME ,ISNULL([2016],0)AS [Cnt2016],ISNULL([2017],0)AS [Cnt2017],ISNULL([2018],0)AS [Cnt2018],ISNULL([2019],0)AS [Cnt2019]
FROM (SELECT CLASSID,CNT_YEAR,CLASSNAME
      FROM CTEDATA) AS D
PIVOT(COUNT(D.CNT_YEAR) FOR D.CNT_YEAR
				IN([2016],[2017],[2018],[2019])
				) AS PVT
ORDER BY PVT.CLASSID;
	

--第七題
SELECT DISTINCT blr.BOOK_ID AS [書本ID],CONVERT(varchar(100), bd.BOOK_BOUGHT_DATE,111) AS [購書日期],CONVERT(varchar(100),blr.LEND_DATE,111) AS [借閱日期],
		(bc.BOOK_CLASS_ID+'-'+bc.BOOK_CLASS_NAME) AS [書籍類別],(blr.KEEPER_ID+'-'+mm.USER_CNAME+'('+mm.USER_ENAME+')') AS [借閱人],
		(bd.BOOK_STATUS+'-'+bcd.CODE_NAME) AS [狀態],(bd.BOOK_AMOUNT) AS [購書金額]
FROM BOOK_DATA bd,BOOK_LEND_RECORD blr,BOOK_CLASS bc,BOOK_CODE bcd,MEMBER_M mm
WHERE bc.BOOK_CLASS_ID = bd.BOOK_CLASS_ID
	AND bd.BOOK_ID = blr.BOOK_ID
	AND bcd.CODE_ID = bd.BOOK_STATUS
	AND blr.KEEPER_ID = mm.USER_ID
	--AND bd.BOOK_KEEPER = mm.USER_ID
	AND mm.USER_CNAME = '李四'
ORDER BY blr.BOOK_ID DESC

--8第八題

INSERT INTO BOOK_LEND_RECORD(BOOK_ID,KEEPER_ID,LEND_DATE) VALUES(N'2004',N'0002','2019/01/02')
UPDATE BOOK_LEND_RECORD
SET LEND_DATE = '2019/01/02'
WHERE KEEPER_ID = '0002'

--第九題
DELETE 
FROM BOOK_LEND_RECORD
WHERE BOOK_ID = '2004'


